export {
  BUILD_RECIPE_ENVIRONMENT_KEYS,
  BUILD_RECIPE_TOOL_KEYS,
  type BuildRecipeDependency,
  type BuildRecipeFileFingerprint,
  type BuildRecipePackageFingerprint,
  type BuildRecipeQueryRecord,
  type BuildRecipeToolFingerprint,
  type BuildRecipeToolKey,
  validateZigBuildRecipe,
  ZIG_BUILD_CONTRACT_VERSION,
  ZIG_BUILD_RECIPE_SCHEMA_VERSION,
  ZIG_INSTALL_VERIFIER_CONTRACT_VERSION,
  type ZigBuildRecipeV1,
} from "./build_recipe.ts";
export {
  BUILD_MANIFEST_FILE,
  BUILD_MANIFEST_SCHEMA_VERSION,
  CLI_JSON_SCHEMA_VERSION,
  CONFIG_SCHEMA_VERSION,
  DOCS_MANIFEST_FILE,
  DOCS_MANIFEST_SCHEMA_VERSION,
  INITIAL_ZIG_SELECTOR,
  MEGA_FORMAT_VERSION,
  MINIMUM_DENO_VERSION,
  MINIMUM_FREE_DISK_BYTES,
  MINIMUM_GIT_VERSION,
  MINIMUM_TOOLS,
  type MinimumToolVersions,
  RECOMMENDED_FREE_DISK_BYTES,
  RECOMMENDED_MEMORY_BYTES,
  STATE_SCHEMA_VERSION,
  SUPPORTED_DOCS_ASSET_CONTRACT,
  type SupportedDocsAssetContract,
  ZIG_MANAGER_CONFIG_FILE,
  ZIG_MANAGER_STATE_FILE,
  ZIG_MANAGER_VERSION,
} from "./constants.ts";
export { loadZigManagerConfig, resolveZigManagerConfig } from "./config.ts";
export {
  ARCH_INSTALL_WARNING,
  archInstallCommand,
  ArchPackageVerifier,
  archPackageVersionAtLeast,
  PACMAN_EXECUTABLE,
} from "./arch_packages.ts";
export {
  BuildManifestValidationError,
  BuildPrerequisiteError,
  ConfigNotFoundError,
  ConfigValidationError,
  DocsBuildRequiredError,
  DocsManifestValidationError,
  InvalidZigSelectorError,
  MegaDocsUnsupportedFormatError,
  ZigBinaryNotBuiltError,
  ZigBinaryVerificationError,
  ZigBuildError,
  ZigDependencyInUseError,
  ZigDocsBuildError,
  ZigDocsOutputError,
  ZigFallbackNotFoundError,
  ZigHostUnsupportedError,
  ZigInstallCorruptError,
  ZigInstallInUseError,
  ZigInstallNotFoundError,
  ZigInvalidArgumentError,
  ZigIoError,
  ZigManagerError,
  type ZigManagerErrorCode,
  ZigOperationAbortedError,
  ZigPathOutsideRootError,
  ZigProcessError,
  ZigProfileInvalidError,
  ZigProfileNotFoundError,
  ZigPurgeConfirmationError,
  ZigReleaseUnsupportedError,
  ZigScopeNotPinnedError,
  ZigShellUnsupportedError,
  ZigSourceNotReadyError,
  ZigStateValidationError,
  ZigVersionNotFoundError,
  ZlsCompatibilityNotFoundError,
} from "./errors.ts";
export {
  CANONICAL_ZIG_REPOSITORY_URL,
  DEFAULT_GLOBAL_CONFIG,
  type GlobalConfig,
  type GlobalConfigDocument,
  GlobalConfigStore,
  GlobalConfigValidationError,
  resolveGlobalConfig,
  validateGlobalConfigDocument,
} from "./global_config.ts";
export {
  computeScopeOperationLockKey,
  GlobalOperationLockManager,
  type GlobalOperationLockTarget,
} from "./global_operation_lock.ts";
export { type CatalogV3, GlobalCatalog } from "./global_catalog.ts";
export {
  computeInstallationId,
  type InstallComponent,
  type InstalledObject,
  type InstallInspection,
  type InstallManifestV3,
  InstallStore,
  InstallStoreError,
  type ResolvedSource,
  type RuntimeDependencyInspector,
  type RuntimeDependencyRecord,
  type RuntimeLinkageRecord,
  type StoredInstallMetadata,
} from "./install_store.ts";
export {
  createBuiltZigInstallIdentity,
  installBuiltZig,
  reuseInstalledZig,
  verifyInstalledZig,
} from "./install_pipeline.ts";
export {
  type PreparedZigBuildRecipe,
  prepareZigBuildRecipe,
  type PrepareZigBuildRecipeInput,
} from "./recipe_preparation.ts";
export {
  LINUX_RUNTIME_INSPECTOR_CONTRACT_VERSION,
  LinuxRuntimeDependencyInspector,
} from "./runtime_dependencies.ts";
export { type Elf64X86_64Info, inspectElf64X86_64 } from "./elf.ts";
export { PlatformPaths, resolvePlatformPaths } from "./platform_paths.ts";
export {
  ProfileStore,
  ProfileStoreError,
  type StoredToolchainProfileMetadata,
  ToolchainProfileStore,
  type ToolchainProfileV1,
} from "./profile_store.ts";
export { removeScopePin, ScopePinStore, writeScopePin } from "./scope_pin.ts";
export {
  parseScopePin,
  resolveScopePin,
  ScopePinError,
  ScopeResolver,
  serializeScopePin,
} from "./scope_resolver.ts";
export {
  type ClassifiedScopeRegistryEntry,
  parseScopeRegistry,
  readScopeRegistry,
  SCOPE_REGISTRY_MAX_BYTES,
  SCOPE_REGISTRY_MAX_OPERATION_LENGTH,
  SCOPE_REGISTRY_MAX_SCOPES,
  SCOPE_REGISTRY_SCHEMA_VERSION,
  type ScopeRegistryClassification,
  type ScopeRegistryEntryV1,
  type ScopeRegistryInspection,
  type ScopeRegistryKnownPin,
  type ScopeRegistryProfileReferences,
  ScopeRegistryStore,
  type ScopeRegistryV1,
  ScopeRegistryValidationError,
  serializeScopeRegistry,
  validateScopeRegistry,
} from "./scope_registry.ts";
export {
  generateBashActivation,
  generateBashDeactivation,
  installSessionShims,
  SessionShimManager,
} from "./session_shim.ts";
export { SourceWorkspace } from "./source_workspace.ts";
export {
  type BuildCommandContext,
  type DocsCommandContext,
  type ReleaseAdapter,
  type ReleaseArchPackageConstraint,
  type ReleaseDevelopmentHeader,
  type ReleaseDevelopmentLibrary,
  type ReleaseGeneratorRequirement,
  type ReleaseRequirements,
  type ReleaseToolKey,
  type ReleaseToolRequirement,
  ZigCMake21Adapter,
  ZigCMake22Adapter,
} from "./release_adapter.ts";
export {
  DenoDiagnosticProbe,
  type DiagnosticProbe,
  type DiagnosticResourcePaths,
  inspectDiagnosticResources,
} from "./resource_diagnostics.ts";
export {
  deriveZigSourceVersion,
  parseCmakeZigSourceContract,
  parseCmakeZigVersion,
  readZigSourceMetadata,
  readZigSourceVersion,
  validateZigSourceVersion,
  ZIG_CMAKE_SOURCE_CONTRACT,
  type ZigCMakeSourceContract,
  type ZigCMakeSourceEvidence,
  type ZigSourceMetadata,
} from "./source_version.ts";
export {
  compareZigVersions,
  listStableZigVersions,
  parseZigSelector,
  parseZigTag,
  resolveZigSelector,
} from "./versions.ts";
export {
  ZigManager,
  type ZigManagerHostSupport,
  type ZigManagerOptions,
  type ZigManagerProgress,
  type ZigManagerServices,
} from "./zig_manager.ts";
export type {
  ActiveBuildState,
  ActiveDocsState,
  ArtifactStatus,
  BuildArtifactPaths,
  BuildIdentityInput,
  BuildManifest,
  BuildOptions,
  BuildResult,
  BuildToolchain,
  CheckoutResult,
  CommandRecord,
  CurrentOptions,
  DiagnosticCacheResult,
  DiagnosticCode,
  DiagnosticCommandData,
  DiagnosticCounts,
  DiagnosticFallbackResult,
  DiagnosticFilesystemKind,
  DiagnosticFilesystemResult,
  DiagnosticFinding,
  DiagnosticMemoryResult,
  DiagnosticResourceResult,
  DiagnosticSessionResult,
  DiagnosticSeverity,
  DiagnosticSourceResult,
  DiagnosticVerificationResult,
  DocsArtifact,
  DocsManifest,
  DocsOptions,
  DocsResult,
  DoctorOptions,
  GcOptions,
  GitRef,
  InstallOptions,
  ManagedZigEnvironment,
  MegaDocsRecord,
  NormalizedBuildOptions,
  OperationOptions,
  ProcessRequest,
  ProcessResult,
  ProcessRunner,
  ProcessStatus,
  PurgeOptions,
  RedactedEffectiveGlobalConfig,
  RemoteHead,
  RemoteRef,
  RepairOptions,
  RepositoryStatus,
  ResolvedZigManagerConfig,
  ResolvedZigSelection,
  RevisionDescription,
  RunOptions,
  ScopeOperationOptions,
  SetupResult,
  SourceRefApi,
  SourceRefDoctorResult,
  SourceSelectionState,
  ToolProbeResult,
  UninstallOptions,
  UseOptions,
  VerifiedArchPackageHint,
  ZigBuildProfile,
  ZigBuildStrategy,
  ZigDanglingScopePin,
  ZigDoctorResult,
  ZigGcResult,
  ZigInstallResult,
  ZigListResult,
  ZigManagerBuildConfig,
  ZigManagerConfig,
  ZigManagerDocsConfig,
  ZigManagerDoctorResult,
  ZigManagerHost,
  ZigManagerHostDiagnostic,
  ZigManagerState,
  ZigManagerStatus,
  ZigManagerToolConfig,
  ZigManagerWarningConfig,
  ZigPurgeResult,
  ZigRepairRegistryStatus,
  ZigRepairResult,
  ZigScopeRegistryState,
  ZigScopeRegistryStatus,
  ZigSelector,
  ZigSemanticVersion,
  ZigShellStatus,
  ZigSourceVersion,
  ZigSyncResult,
  ZigUninstallResult,
  ZigUnuseResult,
  ZigUpdateResult,
  ZigUseResult,
} from "./types.ts";
