import { dirname, isAbsolute, join, resolve } from "@std/path";
import {
  PROFILE_ID_LENGTH,
  SCOPE_DIRECTORY_NAME,
  SCOPE_FORMAT_HEADER,
  SCOPE_PIN_FILE_NAME,
  SCOPE_PIN_SIZE_WITH_FINAL_NEWLINE,
  SCOPE_PIN_SIZE_WITHOUT_FINAL_NEWLINE,
} from "./scope_resolver.ts";

export type ResolverTool = "zig" | "zls";

export interface SessionShimPaths {
  readonly dataDir: string;
  readonly shimsDir?: string;
  readonly profilesDir?: string;
}

export interface InstalledSessionShims {
  readonly zig: string;
  readonly zls: string;
}

export class SessionShimError extends Error {
  readonly code = "ZIG_SHIM_INVALID";
  readonly path: string;

  constructor(path: string, reason: string, options?: ErrorOptions) {
    super(`Invalid zig-manager session shim path '${path}': ${reason}`, options);
    this.name = "SessionShimError";
    this.path = path;
  }
}

interface NormalizedSessionShimPaths {
  readonly dataDir: string;
  readonly shimsDir: string;
  readonly profilesDir: string;
}

export class SessionShimManager {
  readonly paths: NormalizedSessionShimPaths;

  constructor(paths: SessionShimPaths) {
    this.paths = normalizePaths(paths);
  }

  script(tool: ResolverTool): string {
    return generatePosixResolverScript(tool, this.paths);
  }

  async install(): Promise<InstalledSessionShims> {
    await ensureManagedDirectories(this.paths);
    const zig = join(this.paths.shimsDir, "zig");
    const zls = join(this.paths.shimsDir, "zls");
    await writeExecutableAtomically(zig, this.script("zig"));
    await writeExecutableAtomically(zls, this.script("zls"));
    return { zig, zls };
  }

  bashActivation(): string {
    return generateBashActivation(this.paths);
  }

  bashDeactivation(): string {
    return generateBashDeactivation();
  }
}

export function generatePosixResolverScript(
  tool: ResolverTool,
  paths: SessionShimPaths,
): string {
  const normalized = normalizePaths(paths);
  const toolLiteral = shellSingleQuote(tool);
  const dataLiteral = shellSingleQuote(normalized.dataDir);
  const shimsLiteral = shellSingleQuote(normalized.shimsDir);
  const profilesLiteral = shellSingleQuote(normalized.profilesDir);

  return [
    "#!/bin/sh",
    "# Generated by zig-manager. Do not edit.",
    `zm_tool=${toolLiteral}`,
    `zm_data_dir=${dataLiteral}`,
    `zm_shims_dir=${shimsLiteral}`,
    `zm_profiles_dir=${profilesLiteral}`,
    "",
    "zm_pin_failure() {",
    '  printf "zig-manager: broken explicit %s pin at %s: %s; run \'zm current\', \'zm use\', or \'zm repair\'\\n" "$zm_tool" "$zm_pin" "$1" >&2',
    "  exit 126",
    "}",
    "",
    "if ! CDPATH= cd -P .; then",
    "  printf 'zig-manager: cannot resolve the physical working directory\\n' >&2",
    "  exit 126",
    "fi",
    "zm_start_dir=$PWD",
    "zm_scope_dir=$zm_start_dir",
    "zm_pin=",
    "while :; do",
    `  zm_metadata_candidate=$zm_scope_dir/${SCOPE_DIRECTORY_NAME}`,
    `  zm_candidate=$zm_scope_dir/${SCOPE_DIRECTORY_NAME}/${SCOPE_PIN_FILE_NAME}`,
    '  if [ -e "$zm_metadata_candidate" ] || [ -L "$zm_metadata_candidate" ]; then',
    '    if [ ! -d "$zm_metadata_candidate" ] || [ -L "$zm_metadata_candidate" ]; then',
    "      zm_pin=$zm_candidate",
    `      zm_pin_failure "${SCOPE_DIRECTORY_NAME} is not a physical directory"`,
    "    fi",
    '    if [ ! -x "$zm_metadata_candidate" ]; then',
    "      zm_pin=$zm_candidate",
    `      zm_pin_failure "${SCOPE_DIRECTORY_NAME} is not searchable"`,
    "    fi",
    "  fi",
    '  if [ -e "$zm_candidate" ] || [ -L "$zm_candidate" ]; then',
    "    zm_pin=$zm_candidate",
    "    break",
    "  fi",
    '  if [ "$zm_scope_dir" = / ]; then',
    "    break",
    "  fi",
    "  zm_scope_dir=${zm_scope_dir%/*}",
    '  if [ -z "$zm_scope_dir" ]; then zm_scope_dir=/; fi',
    "done",
    "",
    'if [ -n "$zm_pin" ]; then',
    "  zm_metadata_dir=${zm_pin%/toolchain}",
    '  if [ ! -d "$zm_metadata_dir" ] || [ -L "$zm_metadata_dir" ]; then',
    `    zm_pin_failure \"${SCOPE_DIRECTORY_NAME} is not a physical directory\"`,
    "  fi",
    '  if [ ! -f "$zm_pin" ] || [ -L "$zm_pin" ]; then',
    "    zm_pin_failure 'toolchain is not a physical regular file'",
    "  fi",
    "  zm_byte_count=$(command -p wc -c < \"$zm_pin\") || zm_pin_failure 'toolchain cannot be read'",
    '  zm_byte_count=${zm_byte_count#"${zm_byte_count%%[![:space:]]*}"}',
    '  zm_byte_count=${zm_byte_count%"${zm_byte_count##*[![:space:]]}"}',
    `  case \"$zm_byte_count\" in ${SCOPE_PIN_SIZE_WITHOUT_FINAL_NEWLINE}|${SCOPE_PIN_SIZE_WITH_FINAL_NEWLINE}) ;; *) zm_pin_failure 'expected exactly two protocol lines' ;; esac`,
    "",
    "  if ! {",
    "    if IFS= read -r zm_line1; then zm_read1=0; else zm_read1=$?; fi",
    "    if IFS= read -r zm_line2; then zm_read2=0; else zm_read2=$?; fi",
    "    if IFS= read -r zm_extra; then zm_read3=0; else zm_read3=$?; fi",
    '  } < "$zm_pin"; then',
    "    zm_pin_failure 'toolchain cannot be opened'",
    "  fi",
    `  if [ \"$zm_read1\" -ne 0 ] || [ \"$zm_line1\" != ${
      shellSingleQuote(SCOPE_FORMAT_HEADER)
    } ]; then`,
    "    zm_pin_failure 'invalid protocol header'",
    "  fi",
    '  if [ "$zm_read2" -ne 0 ] && [ -z "$zm_line2" ]; then',
    "    zm_pin_failure 'missing profile line'",
    "  fi",
    '  if [ "$zm_read3" -eq 0 ] || [ -n "$zm_extra" ]; then',
    "    zm_pin_failure 'unexpected extra protocol line'",
    "  fi",
    '  case "$zm_line2" in',
    "    profile=*) zm_profile_id=${zm_line2#profile=} ;;",
    "    *) zm_pin_failure \"second line must begin with 'profile='\" ;;",
    "  esac",
    `  if [ \"\${#zm_profile_id}\" -ne ${PROFILE_ID_LENGTH} ]; then`,
    "    zm_pin_failure 'profile ID must be 64 lowercase hexadecimal characters'",
    "  fi",
    '  case "$zm_profile_id" in',
    "    *[!0123456789abcdef]*) zm_pin_failure 'profile ID must be 64 lowercase hexadecimal characters' ;;",
    "  esac",
    "",
    '  if [ ! -d "$zm_profiles_dir" ] || [ -L "$zm_profiles_dir" ]; then',
    "    zm_pin_failure 'manager profile root is missing or unsafe'",
    "  fi",
    "  zm_profile_dir=$zm_profiles_dir/$zm_profile_id",
    '  if [ ! -d "$zm_profile_dir" ] || [ -L "$zm_profile_dir" ]; then',
    '    zm_pin_failure "profile $zm_profile_id is missing or invalid"',
    "  fi",
    "  zm_tool_path_file=$zm_profile_dir/$zm_tool.path",
    '  if [ -L "$zm_tool_path_file" ]; then',
    '    zm_pin_failure "$zm_tool.path is not a physical regular file"',
    "  fi",
    '  if [ ! -f "$zm_tool_path_file" ]; then',
    '    if [ "$zm_tool" = zls ]; then',
    '      printf "zig-manager: profile %s selected at %s has no managed zls; run \'zm use ... --with-zls\'\\n" "$zm_profile_id" "$zm_scope_dir" >&2',
    "      exit 126",
    "    fi",
    '    zm_pin_failure "profile $zm_profile_id has no $zm_tool.path"',
    "  fi",
    "  if ! {",
    "    if IFS= read -r zm_target; then zm_target_read=0; else zm_target_read=$?; fi",
    "    if IFS= read -r zm_target_extra; then zm_target_extra_read=0; else zm_target_extra_read=$?; fi",
    '  } < "$zm_tool_path_file"; then',
    '    zm_pin_failure "$zm_tool.path cannot be opened"',
    "  fi",
    '  if { [ "$zm_target_read" -ne 0 ] && [ -z "$zm_target" ]; } || [ -z "$zm_target" ]; then',
    '    zm_pin_failure "$zm_tool.path is empty"',
    "  fi",
    '  if [ "$zm_target_extra_read" -eq 0 ] || [ -n "$zm_target_extra" ]; then',
    '    zm_pin_failure "$zm_tool.path must contain exactly one path"',
    "  fi",
    '  case "$zm_target" in',
    '    "$zm_data_dir"/installs/*) ;;',
    '    *) zm_pin_failure "$zm_tool.path points outside manager installations" ;;',
    "  esac",
    '  case "$zm_target" in',
    '    *//*|*/./*|*/../*|*/.|*/..) zm_pin_failure "$zm_tool.path is not normalized" ;;',
    "  esac",
    "  zm_install_root=$zm_data_dir/installs",
    '  if [ ! -d "$zm_install_root" ] || [ -L "$zm_install_root" ]; then',
    "    zm_pin_failure 'manager installation root is missing or unsafe'",
    "  fi",
    "  zm_target_parent=${zm_target%/*}",
    '  while [ "$zm_target_parent" != "$zm_install_root" ]; do',
    '    case "$zm_target_parent" in "$zm_install_root"/*) ;; *) zm_pin_failure "$zm_tool.path escapes manager installations" ;; esac',
    '    if [ ! -d "$zm_target_parent" ] || [ -L "$zm_target_parent" ]; then',
    '      zm_pin_failure "managed $zm_tool path traverses an unsafe directory"',
    "    fi",
    "    zm_next_parent=${zm_target_parent%/*}",
    '    if [ "$zm_next_parent" = "$zm_target_parent" ]; then',
    '      zm_pin_failure "managed $zm_tool path cannot be validated"',
    "    fi",
    "    zm_target_parent=$zm_next_parent",
    "  done",
    '  if [ ! -f "$zm_target" ] || [ ! -x "$zm_target" ] || [ -L "$zm_target" ]; then',
    '    zm_pin_failure "managed $zm_tool executable is missing or not executable"',
    "  fi",
    "  unset ZM_RESOLVER_FALLBACK",
    '  exec "$zm_target" "$@"',
    '  zm_pin_failure "managed $zm_tool executable could not be started"',
    "fi",
    "",
    'if [ "${ZM_BASE_PATH+x}" != x ]; then',
    '  printf "zig-manager: %s resolver is not in an activated session (ZM_BASE_PATH is unset)\\n" "$zm_tool" >&2',
    "  exit 126",
    "fi",
    'if [ "${ZM_RESOLVER_FALLBACK-}" = "$zm_tool" ]; then',
    '  printf "zig-manager: refusing recursive %s fallback through ZM_BASE_PATH\\n" "$zm_tool" >&2',
    "  exit 126",
    "fi",
    "zm_path_remaining=$ZM_BASE_PATH",
    "while :; do",
    '  case "$zm_path_remaining" in',
    "    *:*)",
    "      zm_path_entry=${zm_path_remaining%%:*}",
    "      zm_path_remaining=${zm_path_remaining#*:}",
    "      zm_path_more=1",
    "      ;;",
    "    *)",
    "      zm_path_entry=$zm_path_remaining",
    "      zm_path_more=0",
    "      ;;",
    "  esac",
    '  if [ -z "$zm_path_entry" ]; then zm_path_entry=.; fi',
    "  zm_fallback=$zm_path_entry/$zm_tool",
    '  if [ -f "$zm_fallback" ] && [ -x "$zm_fallback" ]; then',
    '    if [ "$zm_fallback" = "$zm_shims_dir/$zm_tool" ]; then',
    '      printf "zig-manager: refusing recursive %s fallback through ZM_BASE_PATH\\n" "$zm_tool" >&2',
    "      exit 126",
    "    fi",
    "    PATH=$ZM_BASE_PATH",
    "    ZM_RESOLVER_FALLBACK=$zm_tool",
    "    export PATH ZM_RESOLVER_FALLBACK",
    '    exec "$zm_fallback" "$@"',
    '    printf "zig-manager: fallback %s could not be started: %s\\n" "$zm_tool" "$zm_fallback" >&2',
    "    exit 126",
    "  fi",
    '  if [ "$zm_path_more" -eq 0 ]; then break; fi',
    "done",
    'printf "zig-manager: no fallback %s executable exists on ZM_BASE_PATH\\n" "$zm_tool" >&2',
    "exit 127",
    "",
  ].join("\n");
}

export function generateBashActivation(paths: SessionShimPaths): string {
  const normalized = normalizePaths(paths);
  if (normalized.shimsDir.includes(":")) {
    throw new SessionShimError(normalized.shimsDir, "a Bash PATH entry cannot contain ':'");
  }

  return [
    "__zig_manager_activate_v1() {",
    `  local zm_new_shim=${shellSingleQuote(normalized.shimsDir)}`,
    `  local zm_data_dir=${shellSingleQuote(normalized.dataDir)}`,
    `  local zm_profiles_dir=${shellSingleQuote(normalized.profilesDir)}`,
    "  local zm_was_active=${ZM_SESSION_ACTIVE-}",
    "  local zm_previous_shim=${ZM_SHIM_DIR-}",
    "  local zm_path_value=${PATH-}",
    "  local zm_path_part zm_path_more",
    "  local -a zm_path_parts=()",
    "  while :; do",
    "    if [[ $zm_path_value == *:* ]]; then",
    "      zm_path_part=${zm_path_value%%:*}",
    "      zm_path_value=${zm_path_value#*:}",
    "      zm_path_more=1",
    "    else",
    "      zm_path_part=$zm_path_value",
    "      zm_path_more=0",
    "    fi",
    '    if [[ $zm_path_part != "$zm_new_shim" && ( $zm_was_active != 1 || -z $zm_previous_shim || $zm_path_part != "$zm_previous_shim" ) ]]; then',
    '      zm_path_parts+=("$zm_path_part")',
    "    fi",
    "    (( zm_path_more )) || break",
    "  done",
    "  local IFS=: ",
    "  local zm_clean_path=${zm_path_parts[*]}",
    "  if [[ $zm_was_active != 1 || ${ZM_BASE_PATH+x} != x ]]; then",
    "    ZM_BASE_PATH=$zm_clean_path",
    "    export ZM_BASE_PATH",
    "  fi",
    "  ZM_SESSION_ACTIVE=1",
    "  ZM_DATA_DIR=$zm_data_dir",
    "  ZM_SHIM_DIR=$zm_new_shim",
    "  ZM_PROFILES_DIR=$zm_profiles_dir",
    "  PATH=$zm_new_shim:$zm_clean_path",
    "  unset ZM_RESOLVER_FALLBACK",
    "  export ZM_SESSION_ACTIVE ZM_DATA_DIR ZM_SHIM_DIR ZM_PROFILES_DIR PATH",
    "  hash -r 2>/dev/null || :",
    "}",
    "__zig_manager_activate_v1",
    "unset -f __zig_manager_activate_v1",
    "",
  ].join("\n");
}

export function generateBashDeactivation(): string {
  return [
    "__zig_manager_deactivate_v1() {",
    "  if [[ ${ZM_SESSION_ACTIVE-} == 1 && -n ${ZM_SHIM_DIR-} ]]; then",
    "    local zm_remove_shim=$ZM_SHIM_DIR",
    "    local zm_path_value=${PATH-}",
    "    local zm_path_part zm_path_more",
    "    local -a zm_path_parts=()",
    "    while :; do",
    "      if [[ $zm_path_value == *:* ]]; then",
    "        zm_path_part=${zm_path_value%%:*}",
    "        zm_path_value=${zm_path_value#*:}",
    "        zm_path_more=1",
    "      else",
    "        zm_path_part=$zm_path_value",
    "        zm_path_more=0",
    "      fi",
    '      if [[ $zm_path_part != "$zm_remove_shim" ]]; then',
    '        zm_path_parts+=("$zm_path_part")',
    "      fi",
    "      (( zm_path_more )) || break",
    "    done",
    "    local IFS=: ",
    "    PATH=${zm_path_parts[*]}",
    "    export PATH",
    "    hash -r 2>/dev/null || :",
    "  fi",
    "  unset ZM_SESSION_ACTIVE ZM_BASE_PATH ZM_DATA_DIR ZM_SHIM_DIR ZM_PROFILES_DIR",
    "  unset ZM_RESOLVER_FALLBACK",
    "}",
    "__zig_manager_deactivate_v1",
    "unset -f __zig_manager_deactivate_v1",
    "",
  ].join("\n");
}

export async function installSessionShims(
  paths: SessionShimPaths,
): Promise<InstalledSessionShims> {
  return await new SessionShimManager(paths).install();
}

function normalizePaths(paths: SessionShimPaths): NormalizedSessionShimPaths {
  const dataDir = normalizeAbsolutePath(paths.dataDir);
  const shimsDir = normalizeAbsolutePath(paths.shimsDir ?? join(dataDir, "shims"));
  const profilesDir = normalizeAbsolutePath(paths.profilesDir ?? join(dataDir, "profiles"));
  if (shimsDir !== join(dataDir, "shims")) {
    throw new SessionShimError(
      shimsDir,
      "shim directory must be the data directory's 'shims' child",
    );
  }
  if (profilesDir !== join(dataDir, "profiles")) {
    throw new SessionShimError(
      profilesDir,
      "profile directory must be the data directory's 'profiles' child",
    );
  }
  return { dataDir, shimsDir, profilesDir };
}

function normalizeAbsolutePath(path: string): string {
  if (path.length === 0 || !isAbsolute(path)) {
    throw new SessionShimError(path, "path must be absolute");
  }
  if (hasControlCharacter(path)) {
    throw new SessionShimError(path, "path contains a control character");
  }
  const normalized = resolve(path);
  if (normalized === "/") throw new SessionShimError(path, "path must not be the filesystem root");
  return normalized;
}

function shellSingleQuote(value: string): string {
  if (hasControlCharacter(value)) {
    throw new SessionShimError(value, "shell literal contains a control character");
  }
  return `'${value.replaceAll("'", `'\"'\"'`)}'`;
}

async function ensureManagedDirectories(paths: NormalizedSessionShimPaths): Promise<void> {
  await ensurePhysicalDirectory(paths.dataDir, true);
  await ensurePhysicalDirectory(paths.shimsDir, false);
  try {
    const physicalData = await Deno.realPath(paths.dataDir);
    const physicalShims = await Deno.realPath(paths.shimsDir);
    if (dirname(physicalShims) !== physicalData) {
      throw new SessionShimError(paths.shimsDir, "shim directory escapes the physical data root");
    }
  } catch (cause) {
    if (cause instanceof SessionShimError) throw cause;
    throw new SessionShimError(paths.shimsDir, "managed directories cannot be resolved", { cause });
  }
}

async function ensurePhysicalDirectory(path: string, recursive: boolean): Promise<void> {
  try {
    await Deno.mkdir(path, { recursive, mode: 0o755 });
  } catch (cause) {
    if (!(cause instanceof Deno.errors.AlreadyExists)) {
      throw new SessionShimError(path, "directory could not be created", { cause });
    }
  }
  let info: Deno.FileInfo;
  try {
    info = await Deno.lstat(path);
  } catch (cause) {
    throw new SessionShimError(path, "directory cannot be inspected", { cause });
  }
  if (!info.isDirectory || info.isSymlink) {
    throw new SessionShimError(path, "path is not a physical directory");
  }
}

async function writeExecutableAtomically(path: string, text: string): Promise<void> {
  const existing = await lstatIfPresent(path);
  if (existing !== null && (!existing.isFile || existing.isSymlink)) {
    throw new SessionShimError(path, "existing shim is not a physical regular file");
  }
  const temporary = join(dirname(path), `.${path.split("/").at(-1)}.tmp-${crypto.randomUUID()}`);
  try {
    const file = await Deno.open(temporary, { createNew: true, write: true, mode: 0o700 });
    try {
      const bytes = new TextEncoder().encode(text);
      let offset = 0;
      while (offset < bytes.length) offset += await file.write(bytes.subarray(offset));
      await file.sync();
    } finally {
      file.close();
    }
    await Deno.chmod(temporary, 0o755);
    await Deno.rename(temporary, path);
  } catch (cause) {
    try {
      await Deno.remove(temporary);
    } catch (cleanupCause) {
      if (!(cleanupCause instanceof Deno.errors.NotFound)) {
        // Preserve the original publication failure.
      }
    }
    if (cause instanceof SessionShimError) throw cause;
    throw new SessionShimError(path, "shim could not be published atomically", { cause });
  }
}

async function lstatIfPresent(path: string): Promise<Deno.FileInfo | null> {
  try {
    return await Deno.lstat(path);
  } catch (cause) {
    if (cause instanceof Deno.errors.NotFound) return null;
    throw new SessionShimError(path, "path cannot be inspected", { cause });
  }
}

function hasControlCharacter(value: string): boolean {
  for (const character of value) {
    const code = character.charCodeAt(0);
    if (code <= 0x1f || code === 0x7f) return true;
  }
  return false;
}
